# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 566)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_sourceServerList = QtWidgets.QLabel(self.centralwidget)
        self.label_sourceServerList.setGeometry(QtCore.QRect(0, 0, 241, 41))
        self.label_sourceServerList.setObjectName("label_sourceServerList")
        self.btn_addSourceServer = QtWidgets.QPushButton(self.centralwidget)
        self.btn_addSourceServer.setGeometry(QtCore.QRect(240, 0, 41, 41))
        self.btn_addSourceServer.setText("")
        self.btn_addSourceServer.setObjectName("btn_addSourceServer")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(290, 10, 521, 511))
        self.groupBox.setObjectName("groupBox")
        self.btn_startS2S = QtWidgets.QPushButton(self.groupBox)
        self.btn_startS2S.setGeometry(QtCore.QRect(130, 120, 261, 61))
        self.btn_startS2S.setObjectName("btn_startS2S")
        self.btn_S2Sresult = QtWidgets.QPushButton(self.groupBox)
        self.btn_S2Sresult.setGeometry(QtCore.QRect(130, 210, 261, 61))
        self.btn_S2Sresult.setObjectName("btn_S2Sresult")
        self.btn_setting = QtWidgets.QPushButton(self.groupBox)
        self.btn_setting.setGeometry(QtCore.QRect(240, 310, 41, 41))
        self.btn_setting.setText("")
        self.btn_setting.setObjectName("btn_setting")
        self.tb_sourceServerList = QtWidgets.QTableView(self.centralwidget)
        self.tb_sourceServerList.setGeometry(QtCore.QRect(0, 40, 281, 481))
        self.tb_sourceServerList.setObjectName("tb_sourceServerList")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_sourceServerList.setText(_translate("MainWindow", "출발지 서버 목록"))
        self.groupBox.setTitle(_translate("MainWindow", "S2S telnet Test"))
        self.btn_startS2S.setText(_translate("MainWindow", "S2S telnet 테스트 시작"))
        self.btn_S2Sresult.setText(_translate("MainWindow", "S2S telnet 테스트 결과 확인"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
